### ISSUE TITLE
Package.json not configured properly

### ISSUE THREAD

**Issue by timothyac** [teslahunt/images#5]
Hey, sweet package! Installed this into a TS project I'm working for on a Tesla app and got some errors because it couldn't find the path to the installed package. Took a peak at your source and noticed that your main file is `generate.js`, but in your package.json you specify index.js as your main target (example down below). I think the solution is to replace `index.js` with `generate.js`.

```js
// Current package.json
{
...
"main": "index.js",
...
}
```

**Comment by timothyac** [comment]
Also for debugging I'm running:
Node v17.6.0
Typescript v3.5.3

**Comment by Kikobeats** [comment]
Hello and thanks for reporting 🙂

It should be fixed at v1.3.0, can you confirm at your end?
